### ISSUE TITLE
Bug: "composes" rule not working on Styles Builder CSS Override files

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#23]
**Describe the bug**
The CSS Modules specification allows composition of classes (see [here](https://github.com/css-modules/css-modules#composition)). But it's not working when I try to use it.
The rule below should make `infoCardSubhead` white, but on the rendered CSS only the font-size rule is applied
```css
.infoCardHeadline {
  color: #ffffff;
}
.infoCardSubhead {
  composes: infoCardHeadline;  
  font-size: 2.25rem;
}
```

This is a simple use case, but on some other cases we are having to duplicate a lot of rules because there is no way to "share" rules and we can only add one modifier class on `blockClass` prop.

**Expected behavior**
`composes: className;` rule on CSS overrides files should work for local-scoped selectors if the selector is a single class name, just like the CSS Modules specification outlines the functionality.
