### ISSUE TITLE
how can I style the tab-layout buttons

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#249]
**What are you trying to accomplish? Please describe.**  

I would like to style the buttons on the tab-layout.list. I tried but without success

I tried to use his css handles but without success.
if I try to stylize it via workaroud it will affect all the buttons in the store

**Additional info**  
 
![Capturar](https://user-images.githubusercontent.com/4852136/77672192-59f89780-6f67-11ea-9e0a-baf9f43e2286.PNG)

I would like an example that could help me

| Account | Workspace |
|---|---|
| fensacl| https://store2--fensacl.myvtex.com/ |

**Comment by klzns** [comment]
Try this
```css
/* vtex.tab-layout.css */
.listItem :global(.vtex-button) {
  color: red;
}
```
