### ISSUE TITLE
Personalize filter-item

### ISSUE THREAD

**Issue by baruchbuc** [vtex-apps/store-discussion#300]
We need put on each filter seccion a diferent style, example on colors put the color correspondent to the filter, filter blue background-color: blue.

**Describe the solution you'd like**
insert classes names at all de filters with the respective value/id, and use it on the css file
<img width="954" alt="Captura de Pantalla 2020-05-19 a la(s) 19 12 53" src="https://user-images.githubusercontent.com/48222250/82390733-1e2cfc00-9a05-11ea-82fa-bbf75614a211.png">
<img width="313" alt="Captura de Pantalla 2020-05-19 a la(s) 19 13 41" src="https://user-images.githubusercontent.com/48222250/82390738-208f5600-9a05-11ea-98e3-bc5cdb007bf8.png">

**Comment by klzns** [comment]
I think that's possible doing this:

```css
/* File: vtex.search-result.css */
.filterItem--filtersContainer--ocean-blue :global(.vtex-checkbox__label) {
  background: blue;
}
```
