### ISSUE TITLE
No CSS Handler for add-to-cart-button Button element

### ISSUE THREAD

**Issue by leomuzicarvalho** [vtex-apps/store-discussion#452]
Hi, I'm trying to do some customizations to the add-to-cart-button, but I didn't find any handler to add some style to it:

![image](https://user-images.githubusercontent.com/45275689/95076811-d6272100-06e8-11eb-92c6-cffa7095da7b.png)

Is there a way to make it work? I'm facing the same problem with store-form lables and button.

What I want to do is something simple like this, but I lack the handler for the whole button:

![image](https://user-images.githubusercontent.com/45275689/95077148-636a7580-06e9-11eb-9c93-4fe5a96ea67f.png)

Thanks in advance!

**Comment by juliomoreira** [comment]
Hi @leomuzicarvalho there's a couple of ways you can target the `.vtex-button` class in your CSS overrides, the simpler one is to use `:global()` selector in your case specifically you could use some product-summary handle to target the add-to-cart-button specifically, like so:

```css
/* styles/css/vtex.product-summary.css */
.container :global(.vtex-button) {
  position: absolute;
  ...
}
```

Another approach would be to wrap your button in a `flex-layout` block, give the block a `blockClass` like `product-summary-button` and apply the stylings based on the flex-layout block, so you would have:

```jsonc
// store/blocks.jsonc
{
  "flex-layout.row#product-summary-button": {
    "children": ["add-to-cart-button"],
    "props": {
      "blockClass": "product-summary-button"
    }
  }
}
```

and then

```css
/* styles/css/vtex.flex-layout.css */
.flexRow--product-summary-button :global(.vtex-button) {
  position: absolute;
  ...
}
```

Hope it helps,
