### ISSUE TITLE
@keyframes with `from` and `to` is not deprecated CSS

### ISSUE THREAD

**Issue by HugoLaguna** [vtex-apps/store-discussion#615]
# overview

I can create @keyframe animations with CSS but i can't use `from` and `to` 

example:

**nor allowed** 
```css
@keyframes fadeId {
  from{ opacity: 0;}
  to{ opacity: 1;}
}
```

**allowed**
```css
@keyframes fadeId {
  0%{ opacity: 0;}
 100%{ opacity: 1;}
}
```

## Expectation

That is not deprecated CSS, it is absurd message,
https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes

## Alternative

We can commit this issue on this documentation  => https://vtex.io/docs/releases/2019-week-43-44/css-selectors-deprecation?utm_source=toolbelt/

## Evidences
![image](https://user-images.githubusercontent.com/33559104/126485649-e36d07b4-67bf-4d4a-b686-d8c8dd93926d.png)
